services:
  bot:
    build:
      ./Bot
    volumes:
      - ./Bot:/app
    networks:
      - app-network
    depends_on:
      Redis:
        condition: service_healthy
      #- Api
    env_file:
      - .env

  
  #Api:
    #build:
      #context: ./Api
    #ports:
      #- 443:443
      #- 80:80
    #volumes:
      #- ./Api:/api
    #networks:
      #- app-network
    #depends_on:
      #- Redis
    #env_file:
      #- .env
  
  Redis:
    image: redis:latest
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}", "--bind", "0.0.0.0"]
    healthcheck:
      test: ["CMD", "redis-cli", "-h", "Redis", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    networks:
      - app-network
    volumes:
      - redis-data:/data
  
networks:
  app-network:
    driver: bridge

volumes:
  redis-data:
    driver: local