#temporarily store tiles here
def tiles() -> list[str]:
    tiles = [
"Complete a Godsword (blade 1, 2, 3 + hilt) (1,1)",
"Obtain 2 of the Wilderness weapon upgrade (skull, claws, fang) or any 1 voidwaker piece (1,2)",
"Obtain 2 Tormented Synapses or 2 Burning Claw (1,3)",
"Obtain 2 of the following (Any Keris Partisan Jewel, Dex/Arcane Prayer scroll) (1,4)",
"Defeat Royal Titans 850 times. (1,5)",
"Obtain an Enhanced Crystal Weapon Seed or 4 Crystal Armour seeds. (1,6)",
"Obtain 3 Dragon Pickaxe (2,1)",
"Obtain a Dragon War Hammer (2,2)",
"Subdue Tempoross 400 times (2,3)",
"Obtain 3 different Slayer items (2,4)",
"Obtain 2 of the following (Dragon Harpoon, Drake Unique, or Hydra Unique) (2,5)",
"Obtain 3 of the following (Miscellaneous) (2,6)",
"Obtain 4 Zenyte Shards or a full Ballista (3,1)",
"Obtain any 2 Cerberus Crystals. (3,2)",
"Obtain any Revenant weapon or Emblem 2M+ (3,3)",
"Complete an Abyssal Bludgeon or a Noxious Halberd (3,4)",
"Obtain any unique from Theatre of Blood (Justiciar, Avernic, Staff, Dust, Rapier, Pet, Scythe) (3,5)",
"Subdue Zalcano 800 times. (3,6)",
"Obtain one TOA Unique or Pet (4,1)",
"Obtain 2 of the following Skilling Uniques (4,2)",
"Obtain any 2 unique from Zulrah (excluding onyx) (4,3)",
"Obtain 3 different Quartz Crystals or any Virtus Pieces. (4,4)",
"Obtain 5 Venator Shards (4,5)",
"Obtain any Wilderness Ring. (4,6)",
"Obtain all of the following early ironman items (5,1)",
"Subdue Herbiboar 1500 times (5,2)",
"Obtain any COX Equipment Unique (No Scrolls) (5,3)",
"Complete a full set of either Barrows or Moons of Peril Armour (including weapons) (5,4)",
"Obtain 25 Scurrius Spines (5,5)",
"Obtain any unique from the following bosses: Nex, Corporeal Beast, or Phosani/Nightmare (5,6)",
"Close 400 Guardian Rifts (6,1)",
"Obtain one of each DKS Rings (Berserker, Warrior, Seers, Archer) (6,2)",
"Obtain a complete set of Armadyl (helm, chest, legs) or Bandos Armour (chest, tassets, boots) (6,3)",
"Obtain 10 Hueycoatl Hides and either a Tome of Earth or Dragon Hunter Wand (6,4)",
"Obtain one of the following: Soulreaper Axe piece or Vestige piece (6,5)",
"Obtain 2 of the following (Any Slayer Head, Jar, Imbued Heart, or Eternal Gem) (6,6)",
"Super secret test tile if i forget this in please dont use it, it isnt a real tile (7,1)",
]
    return tiles
